[[redirects]]
  from = "/api/*"
  to = "http://localhost:8080/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws/*"
  to = "http://localhost:8080/ws/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/oauth2/*"
  to = "http://localhost:8080/oauth2/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/login/oauth2/*"
  to = "http://localhost:8080/login/oauth2/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
