[[redirects]]
  from = "/api/*"
  to = "https://3.110.61.209.nip.io/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws/*"
  to = "https://3.110.61.209.nip.io/ws/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/oauth2/*"
  to = "https://3.110.61.209.nip.io/oauth2/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/login/oauth2/*"
  to = "https://3.110.61.209.nip.io/login/oauth2/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
